# Generated by Django 5.0.6 on 2024-05-11 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(default="O'zinggiz haqida ma'lomot....", max_length=600)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('avater', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('country', models.CharField(default='Hi', max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('frinds', models.ManyToManyField(blank=True, related_name='frindes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
