# Generated by Django 5.0.6 on 2024-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='users.profile'),
        ),
    ]
